env: development

service:
  name: message-gateway
  host: 0.0.0.0
  port: 50052
  tags:
    - grpc
    - gateway
    - message
  metadata:
    version: "0.1.0"

log:
  output_dir: logs
  file_prefix: message-gateway
  level: 3  # DEBUG
  max_size: 100
  max_backups: 31
  max_age: 31
  compress: false

consul:
  host: localhost
  port: 8500
  register_interval: 10
  heartbeat_interval: 5

etcd:
  endpoints:
    - localhost:2379
  username: ""
  password: ""
  prefix: "/flare/message"

kafka:
  brokers:
    - localhost:9092
  group_id: message-gateway-dev
  topics:
    - message.send
    - message.deliver
    - message.ack

redis:
  host: localhost
  port: 6379
  password: flare123
  database: 0
  pool_size: 20

extensions:
  rate_limit:
    max_requests: 1000
    interval: 60
  circuit_breaker:
    failure_threshold: 5
    reset_timeout: 60
  retry:
    max_attempts: 3
    initial_interval: 1
    max_interval: 5
    multiplier: 2 