env: testing

service:
  name: message-gateway
  host: 0.0.0.0
  port: 50052
  tags:
    - grpc
    - gateway
    - message
  metadata:
    version: "0.1.0"

log:
  output_dir: /var/log/flare
  file_prefix: message-gateway-test
  level: 3  # DEBUG
  max_size: 200
  max_backups: 31
  max_age: 31
  compress: true

consul:
  host: consul.test.flare
  port: 8500
  register_interval: 10
  heartbeat_interval: 5

etcd:
  endpoints:
    - etcd.test.flare:2379
  username: "flare"
  password: "flare123"
  prefix: "/flare/message"

kafka:
  brokers:
    - kafka.test.flare:9092
  group_id: message-gateway-test
  topics:
    - message.send
    - message.deliver
    - message.ack

redis:
  host: redis.test.flare
  port: 6379
  password: flare123
  database: 0
  pool_size: 50

extensions:
  rate_limit:
    max_requests: 5000
    interval: 60
  circuit_breaker:
    failure_threshold: 5
    reset_timeout: 60
  retry:
    max_attempts: 3
    initial_interval: 1
    max_interval: 5
    multiplier: 2 