version: '3.8'

services:
  consul:
    image: consul:1.15
    container_name: flare_consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./data/consul:/consul/data
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: flare_kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1800000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 20000
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - ./data/kafka:/var/lib/kafka/data

  redis:
    image: redis:7.2-alpine
    container_name: flare_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  minio:
    image: minio/minio:RELEASE.2024-02-24T17-11-14Z
    container_name: flare_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"

  postgresql:
    image: timescale/timescaledb:latest-pg15
    container_name: flare_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flare_im
      POSTGRES_USER: flare
      POSTGRES_PASSWORD: flare123
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: flare_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: flare
      MONGO_INITDB_ROOT_PASSWORD: flare123
      MONGO_INITDB_DATABASE: flare_im
    volumes:
      - ./data/mongodb:/data/db

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: flare_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: flare
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

networks:
  default:
    name: flare_network 