env: production

service:
  name: message-gateway
  host: 0.0.0.0
  port: 50052
  tags:
    - grpc
    - gateway
    - message
  metadata:
    version: "0.1.0"

log:
  output_dir: /var/log/flare
  file_prefix: message-gateway
  level: 2  # INFO
  max_size: 500
  max_backups: 90
  max_age: 90
  compress: true

consul:
  host: consul.service.flare
  port: 8500
  register_interval: 10
  heartbeat_interval: 5

etcd:
  endpoints:
    - etcd-1.service.flare:2379
    - etcd-2.service.flare:2379
    - etcd-3.service.flare:2379
  username: "flare"
  password: "flare123"
  prefix: "/flare/message"

kafka:
  brokers:
    - kafka-1.service.flare:9092
    - kafka-2.service.flare:9092
    - kafka-3.service.flare:9092
  group_id: message-gateway-prod
  topics:
    - message.send
    - message.deliver
    - message.ack

redis:
  host: redis.service.flare
  port: 6379
  password: flare123
  database: 0
  pool_size: 100

extensions:
  rate_limit:
    max_requests: 10000
    interval: 60
  circuit_breaker:
    failure_threshold: 10
    reset_timeout: 120
  retry:
    max_attempts: 5
    initial_interval: 1
    max_interval: 10
    multiplier: 2 