env: development

service:
  name: message-router
  host: 0.0.0.0
  port: 50051
  tags:
    - grpc
    - message
  metadata:
    version: "1.0.0"

log:
  output_dir: logs
  file_prefix: message-router
  level: 3  # DEBUG
  max_size: 100
  max_backups: 31
  max_age: 31
  compress: false

consul:
  host: localhost
  port: 8500
  register_interval: 10
  heartbeat_interval: 5

redis:
  host: localhost
  port: 6379
  password: flare123
  database: 0
  pool_size: 20

kafka:
  brokers:
    - localhost:9092
  group_id: message-router-dev
  topics:
    - message.send
    - message.deliver
    - message.ack

postgres:
  host: localhost
  port: 5432
  database: flare_im_dev
  username: flare
  password: flare123
  pool_size: 20

clickhouse:
  host: localhost
  port: 19000
  database: flare_im_dev
  username: flare
  password: flare123
  pool_size: 10

extensions:
  message_queue:
    max_retry: 3
    retry_interval: 5
    batch_size: 100 