env: testing

service:
  name: message-router
  host: 0.0.0.0
  port: 50051
  tags:
    - grpc
    - message
  metadata:
    version: "1.0.0"

log:
  output_dir: /var/log/flare
  file_prefix: message-router-test
  level: 3  # DEBUG
  max_size: 200
  max_backups: 31
  max_age: 31
  compress: true

consul:
  host: consul.test.flare
  port: 8500
  register_interval: 10
  heartbeat_interval: 5

redis:
  host: redis.test.flare
  port: 6379
  password: flare123
  database: 0
  pool_size: 50

kafka:
  brokers:
    - kafka.test.flare:9092
  group_id: message-router-test
  topics:
    - message.send
    - message.deliver
    - message.ack

postgres:
  host: postgres.test.flare
  port: 5432
  database: flare_im_test
  username: flare
  password: flare123
  pool_size: 50

clickhouse:
  host: clickhouse.test.flare
  port: 9000
  database: flare_im_test
  username: flare
  password: flare123
  pool_size: 20

extensions:
  message_queue:
    max_retry: 3
    retry_interval: 5
    batch_size: 500 