[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
envy.workspace = true

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }